logging:
    level:
        org:
            springframework: INFO
            springframework.security: INFO
spring:
    application:
      name: web-service  # Identify this application
    freemarker:
      enabled: false     # Ignore Eureka dashboard FreeMarker templates
    jackson:
        serialization:
            fail-on-empty-beans: false

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
userInfoUri: https://api.github.com/user

# Discovery Server Access
#  1. Define URL of registration server (defaultZone)
#  2. Reduce lease-renewal time so processes register more quickly
eureka:
  instance:
     leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
port: 3333 # HTTP (Tomcat) port